config/routes.rb
Rails.application.routes.draw do

  root to: 'public/homes#top'

  devise_for :customers, skip: :all

  devise_scope :customer do
    get '/customers/sign_in'     => 'public/sessions#new'
    post '/customers/sign_in'    => 'public/sessions#create'
    delete '/customers/sign_out' => 'public/sessions#destroy'
    get '/customers/sign_up'     => 'public/registrations#new'
    post '/customers'            => 'public/registrations#create'
  end

  scope module: :public do
    resources :items,       only: [:index, :show] do
      resources :cart_items,  only: [:create]
      patch '/cart_items/:id'         => 'cart_items#destroy'
      delete '/cart_items/destroy_all' => 'cart_items#destroy_all'
    end
    resources :cart_items,  only: [:index, :update]
    get  '/orders/thanks'  => 'orders#thanks'
    resources :orders,      only: [:new, :index, :show]
      post '/orders/confirm' => 'orders#confirm'
      post '/orders/decide'  => 'orders#decide'
    resources :addresses,    only: [:index, :create, :edit, :update, :destroy]
    #customersのルーティング
    get '/customers/my_page'     => 'customers#show'
    get '/customers/edit'        => 'customers#edit'
    patch '/customers'           => 'customers#update'
    get '/customers/unsubscribe' => 'customers#unsubscribe'
    patch '/customers/withdraw'  => 'customers#withdraw'
  end

  devise_for :admins, skip: :all
  devise_scope :admin do
    get '/admin/sign_in'     => 'admin/sessions#new',     as: :new_admin_session
    post '/admin/sign_in'    => 'admin/sessions#create',  as: :admin_session
    delete '/admin/sign_out' => 'admin/sessions#destroy', as: :destroy_admin_session
  end
    namespace :admin do
    resources :items,       except: [:destroy]
    resources :genres,      only: [:index, :create, :edit, :update]
    resources :customers,   only: [:index, :show, :edit, :update]
    resources :orders,      only: [:show, :update] do
      resources :order_items, only: [:update]
    end
  end

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html

  get '/admin' => 'admin/homes#top'
  get '/about' => 'public/homes#about'

end

app/models/address.rb
class Address < ApplicationRecord

  belongs_to :customer

  def full_address
    "〒#{self.postal_code}　#{self.address}　#{self.name}"
  end
end

app/models/admin.rb
class Admin < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable,
         :rememberable, :validatable
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/cart_item.rb
class CartItem < ApplicationRecord

  belongs_to :item
  belongs_to :customer

  def item_subtotal
    amount * item.add_tax_price
  end

end

app/models/customer.rb
class Customer < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  has_many :addresses,  dependent: :destroy
  has_many :cart_items, dependent: :destroy
  has_many :orders,     dependent: :destroy

  def full_name
    self.last_name + self.first_name
  end

end

app/models/genre.rb
class Genre < ApplicationRecord

  has_many :items, dependent: :destroy

end

app/models/item.rb
class Item < ApplicationRecord

  belongs_to :genre, optional: true
  has_many :cart_items, dependent: :destroy
  has_many :order_items, dependent: :destroy
  has_many :orders, through: :order_items

  attachment :image

  def add_tax_price
    (self.price * 1.08).round
  end

end

app/models/order.rb
class Order < ApplicationRecord

  belongs_to :customer
  has_many :order_items
  has_many :items, through: :order_item

  enum payment: {クレジットカード: 0, 銀行振込: 1}
  enum is_active: {入金待ち: 0, 入金確認: 1, 製作中: 2, 発送準備中: 3, 発送済み: 4}

end

app/models/order_item.rb
class OrderItem < ApplicationRecord

  belongs_to :order, dependent: :destroy
  belongs_to :item

  enum is_active: {着手不可: 0, 製作待ち: 1, 製作中: 2, 製作完了: 3}

  def add_tax_price
    (self.price * 1.08).round
  end

  def item_subtotal
    amount * item.add_tax_price
  end

end

app/controllers/admin/customers_controller.rb
class Admin::CustomersController < ApplicationController
  before_action :authenticate_admin!

  def index
    @customers = Customer.page(params[:page])
  end

  def show
    @customer = Customer.find(params[:id])
  end

  def edit
    @customer = Customer.find(params[:id])
  end

  def update
    @customer = Customer.find(params[:id])
    @customer.update(customer_params)
    redirect_to admin_customer_path(@customer.id)
  end

  private

  def customer_params
    params.require(:customer).permit(:last_name, :first_name, :last_name_kana, :first_name_kana, :postal_code, :address, :telephone_number, :telephone_number, :email, :is_active)
  end

end

app/controllers/admin/genres_controller.rb
class Admin::GenresController < ApplicationController
  before_action :authenticate_admin!

  def index
    @genre = Genre.new
    @genres = Genre.all
  end

  def create
    @genre = Genre.new(genre_params)
    @genre.save
    redirect_to admin_genres_path
  end

  def edit
    @genre = Genre.find(params[:id])
  end

  def update
    @genre = Genre.find(params[:id])
    @genre.update(genre_params)
    redirect_to admin_genres_path
  end

  private

  def genre_params
    params.require(:genre).permit(:name)
  end

end

app/controllers/admin/homes_controller.rb
class Admin::HomesController < ApplicationController
  before_action :authenticate_admin!, except: [:top]

  def top
    path = Rails.application.routes.recognize_path(request.referer)

    if path[:controller] == "admin/customers"
      @orders = Order.where(customer_id: path[:id]).page(params[:page])
    else
      @orders = Order.page(params[:page])
    end
  end

end

app/controllers/admin/items_controller.rb
class Admin::ItemsController < ApplicationController
  before_action :authenticate_admin!

  def index
    @items = Item.page(params[:page])
  end

  def new
    @item = Item.new
  end

  def create
    @item = Item.new(item_params)
    @item.save
    redirect_to admin_item_path(@item.id)
  end

  def show
    @item = Item.find(params[:id])
  end

  def edit
    @item = Item.find(params[:id])
  end

  def update
    @item = Item.find(params[:id])
    @item.update(item_params)
    redirect_to admin_item_path(@item.id)
  end

  private

  def item_params
    params.require(:item).permit(:name, :image, :introduction, :price, :is_active, :genre_id)
  end

end

app/controllers/admin/orders_controller.rb
class Admin::OrdersController < ApplicationController
  before_action :authenticate_admin!

  def show
    @order = Order.find(params[:id])
    @order_items = OrderItem.where(order_id: @order)
    @total = 0
      @order_items.each do |i|
          @total += i.item_subtotal
      end
    @total_fee = @total + @order.shipping_fee
  end

  def update
    @order = Order.find(params[:id])
    @order.update(order_params)
    redirect_to admin_order_path(@order.id)
  end

  private

  def order_params
    params.require(:order).permit(:is_active)
  end

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :configure_permitted_parameters, if: :devise_controller?

  def after_sign_out_path_for(resource)
    root_path
  end

  private

  def configure_permitted_parameters
    added_attrs = [:last_name, :first_name, :last_name_kana, :first_name_kana, :email, :postal_code, :address, :telephone_number, :password, :password_confirmation]
    devise_parameter_sanitizer.permit :sign_up, keys: added_attrs
    devise_parameter_sanitizer.permit :account_update, keys: added_attrs
  end

end

app/helpers/admin/customers_helper.rb
module Admin::CustomersHelper
end

app/helpers/admin/genres_helper.rb
module Admin::GenresHelper
end

app/helpers/admin/homes_helper.rb
module Admin::HomesHelper
end

app/helpers/admin/items_helper.rb
module Admin::ItemsHelper
end

app/helpers/admin/order_items_helper.rb
module Admin::OrderItemsHelper
end

app/helpers/admin/orders_helper.rb
module Admin::OrdersHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/homes_helper.rb
module HomesHelper
end

app/views/admin/customers/edit.html.erb
<div class="container mt-3">

  <div class="row mt-3 ml-5">
    <h4 class="bg-light"><%= @customer.last_name %><%= @customer.first_name %>さんの会員情報編集</h4>
  </div>

  <div class="row my-3 ml-5">

    <%= form_with model: [:admin, @customer], class: 'form-horizontal w-75', local:true do |f| %>

    <div class="form-group row">
      <label class="col-md-2 col-form-label">会員ID</label>
      <div class="col-md-7">
        <%= @customer.id %>
      </div>
    </div>

    <div class="form-group row">
      <label class="col-md-2 col-form-label">氏名</label>
      <div class="form-inline col-md-7">
        <%= f.text_field :last_name, class: 'mr-2' %><%= f.text_field :first_name %>
      </div>
    </div>

    <div class="form-group row">
      <label class="col-md-2 col-form-label">フリガナ</label>
      <div class="form-inline col-md-7">
        <%= f.text_field :last_name_kana, class: 'mr-2' %><%= f.text_field :first_name_kana %>
      </div>
    </div>

    <div class="form-group row">
      <label class="col-md-2 col-form-label">郵便番号</label>
      <div class="col-md-7">
        <%= f.text_field :postal_code %>
      </div>
    </div>

    <div class="form-group row">
      <label class="col-md-2 col-form-label">住所</label>
      <div class="col-md-7">
        <%= f.text_field :address %>
      </div>
    </div>

    <div class="form-group row">
      <label class="col-md-2 col-form-label">電話番号</label>
      <div class="col-md-7">
        <%= f.text_field :telephone_number %>
      </div>
    </div>

    <div class="form-group row">
      <label class="col-md-2 col-form-label">メールアドレス</label>
      <div class="col-md-7">
        <%= f.text_field :email %>
      </div>
    </div>

    <div class="form-group row">
      <label class="col-md-2 col-form-label">会員ステータス</label>
      <div class="col-md-7">
        <div class="d-inline mr-3">
          <%= f.radio_button :is_active, true, checked: true %>
          <%= f.label :is_active, '有効', value: true %>
        </div>
        <div class="d-inline">
          <%= f.radio_button :is_active, false %>
          <%= f.label :is_active, '退会', value: false %>
        </div>
      </div>
    </div>

    <div class="form-group row">
      <div class="col-md-4"></div>
      <div class="col-md-4">
        <%= f.submit "変更を保存", class: 'btn btn-success' %>
      </div>
    </div>

    <% end %>
  </div>

</div>

app/views/admin/customers/index.html.erb
<div class="container mt-3">

  <div class="row mt-3 ml-5">
    <h4 class="bg-light">会員一覧</h4>
  </div>

  <div class="row my-3">
    <table class="table w-75 mx-auto">
      <thead class="thead-light">
        <tr>
          <th>会員ID</th>
          <th>氏名</th>
          <th>メールアドレス</th>
          <th>ステータス</th>
        </tr>
      </thead>
      <tbody>
        <% @customers.each do |customer| %>
        <tr>
          <td><%= customer.id %></td>
          <td>
            <%= link_to admin_customer_path(customer.id) do %>
              <%= customer.last_name %><%= customer.first_name %>
            <% end %>
          </td>
          <td><%= customer.email %></td>
          <td>
            <% if customer.is_active == true %>
              <p class="text-success">有効</p>
            <% else %>
              <p class="text-muted">退会</p>
            <% end %>
          </td>
        </tr>
        <% end %>
        <%= paginate @customers %>
      </tbody>
    </table>
  </div>

</div>

app/views/admin/customers/show.html.erb
<div class="container mt-3">

  <div class="row mt-3 ml-5">
    <h4 class="bg-light"><%= @customer.last_name %><%= @customer.first_name %>さんの会員詳細</h4>
  </div>

  <div class="row my-3 ml-5">
    <table class="table table-borderless w-auto ml-5">
      <tr>
        <th>会員ID</th>
        <td><%= @customer.id %></td>
      </tr>
      <tr>
        <th>氏名</th>
        <td><%= @customer.last_name %> <%= @customer.first_name %></td>
      </tr>
      <tr>
        <th>フリガナ</th>
        <td><%= @customer.last_name_kana %> <%= @customer.first_name_kana %></td>
      </tr>
      <tr>
        <th>郵便番号</th>
        <td><%= @customer.postal_code %></td>
      </tr>
      <tr>
        <th>住所</th>
        <td><%= @customer.address %></td>
      </tr>
      <tr>
        <th>電話番号</th>
        <td><%= @customer.telephone_number %></td>
      </tr>
      <tr>
        <th>メールアドレス</th>
        <td><%= @customer.email %></td>
      </tr>
      <tr>
        <th>会員ステータス</th>
        <td>
          <% if @customer.is_active == true %>
            <p class="text-success">有効</p>
          <% else %>
            <p class="text-muted">退会</p>
          <% end %>
        </td>
      </tr>
      <tr>
        <th></th>
        <td>
          <%= link_to "編集する", edit_admin_customer_path(@customer.id), class: 'btn btn-success mr-5' %>
          <%= link_to "注文履歴一覧を見る", admin_path, class: 'btn btn-primary ml-5' %>
        </td>
      </tr>
    </table>
  </div>

</div>