config/routes.rb
Rails.application.routes.draw do

  root to: 'public/homes#top'

  devise_for :customers, skip: :all

  devise_scope :customer do
    get '/customers/sign_in'     => 'public/sessions#new'
    post '/customers/sign_in'    => 'public/sessions#create'
    delete '/customers/sign_out' => 'public/sessions#destroy'
    get '/customers/sign_up'     => 'public/registrations#new'
    post '/customers'            => 'public/registrations#create'
  end

  scope module: :public do
    resources :items,       only: [:index, :show] do
      resources :cart_items,  only: [:create]
      patch '/cart_items/:id'         => 'cart_items#destroy'
      delete '/cart_items/destroy_all' => 'cart_items#destroy_all'
    end
    resources :cart_items,  only: [:index, :update]
    get  '/orders/thanks'  => 'orders#thanks'
    resources :orders,      only: [:new, :index, :show]
      post '/orders/confirm' => 'orders#confirm'
      post '/orders/decide'  => 'orders#decide'
    resources :addresses,    only: [:index, :create, :edit, :update, :destroy]
    #customersのルーティング
    get '/customers/my_page'     => 'customers#show'
    get '/customers/edit'        => 'customers#edit'
    patch '/customers'           => 'customers#update'
    get '/customers/unsubscribe' => 'customers#unsubscribe'
    patch '/customers/withdraw'  => 'customers#withdraw'
  end

  devise_for :admins, skip: :all
  devise_scope :admin do
    get '/admin/sign_in'     => 'admin/sessions#new',     as: :new_admin_session
    post '/admin/sign_in'    => 'admin/sessions#create',  as: :admin_session
    delete '/admin/sign_out' => 'admin/sessions#destroy', as: :destroy_admin_session
  end
    namespace :admin do
    resources :items,       except: [:destroy]
    resources :genres,      only: [:index, :create, :edit, :update]
    resources :customers,   only: [:index, :show, :edit, :update]
    resources :orders,      only: [:show, :update] do
      resources :order_items, only: [:update]
    end
  end

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html

  get '/admin' => 'admin/homes#top'
  get '/about' => 'public/homes#about'

end

app/models/address.rb
class Address < ApplicationRecord

  belongs_to :customer

  def full_address
    "〒#{self.postal_code}　#{self.address}　#{self.name}"
  end
end

app/models/admin.rb
class Admin < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable,
         :rememberable, :validatable
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/cart_item.rb
class CartItem < ApplicationRecord

  belongs_to :item
  belongs_to :customer

  def item_subtotal
    amount * item.add_tax_price
  end

end

app/models/customer.rb
class Customer < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  has_many :addresses,  dependent: :destroy
  has_many :cart_items, dependent: :destroy
  has_many :orders,     dependent: :destroy

  def full_name
    self.last_name + self.first_name
  end

end

app/models/genre.rb
class Genre < ApplicationRecord

  has_many :items, dependent: :destroy

end

app/models/item.rb
class Item < ApplicationRecord

  belongs_to :genre, optional: true
  has_many :cart_items, dependent: :destroy
  has_many :order_items, dependent: :destroy
  has_many :orders, through: :order_items

  attachment :image

  def add_tax_price
    (self.price * 1.08).round
  end

end

app/models/order.rb
class Order < ApplicationRecord

  belongs_to :customer
  has_many :order_items
  has_many :items, through: :order_item

  enum payment: {クレジットカード: 0, 銀行振込: 1}
  enum is_active: {入金待ち: 0, 入金確認: 1, 製作中: 2, 発送準備中: 3, 発送済み: 4}

end

app/models/order_item.rb
class OrderItem < ApplicationRecord

  belongs_to :order, dependent: :destroy
  belongs_to :item

  enum is_active: {着手不可: 0, 製作待ち: 1, 製作中: 2, 製作完了: 3}

  def add_tax_price
    (self.price * 1.08).round
  end

  def item_subtotal
    amount * item.add_tax_price
  end

end

app/controllers/admin/genres_controller.rb
class Admin::GenresController < ApplicationController
  before_action :authenticate_admin!

  def index
    @genre = Genre.new
    @genres = Genre.all
  end

  def create
    @genre = Genre.new(genre_params)
    @genre.save
    redirect_to admin_genres_path
  end

  def edit
    @genre = Genre.find(params[:id])
  end

  def update
    @genre = Genre.find(params[:id])
    @genre.update(genre_params)
    redirect_to admin_genres_path
  end

  private

  def genre_params
    params.require(:genre).permit(:name)
  end

end

app/controllers/admin/homes_controller.rb
class Admin::HomesController < ApplicationController
  before_action :authenticate_admin!, except: [:top]

  def top
    path = Rails.application.routes.recognize_path(request.referer)

    if path[:controller] == "admin/customers"
      @orders = Order.where(customer_id: path[:id]).page(params[:page])
    else
      @orders = Order.page(params[:page])
    end
  end

end

app/controllers/admin/items_controller.rb
class Admin::ItemsController < ApplicationController
  before_action :authenticate_admin!

  def index
    @items = Item.page(params[:page])
  end

  def new
    @item = Item.new
  end

  def create
    @item = Item.new(item_params)
    @item.save
    redirect_to admin_item_path(@item.id)
  end

  def show
    @item = Item.find(params[:id])
  end

  def edit
    @item = Item.find(params[:id])
  end

  def update
    @item = Item.find(params[:id])
    @item.update(item_params)
    redirect_to admin_item_path(@item.id)
  end

  private

  def item_params
    params.require(:item).permit(:name, :image, :introduction, :price, :is_active, :genre_id)
  end

end

app/controllers/admin/orders_controller.rb
class Admin::OrdersController < ApplicationController
  before_action :authenticate_admin!

  def show
    @order = Order.find(params[:id])
    @order_items = OrderItem.where(order_id: @order)
    @total = 0
      @order_items.each do |i|
          @total += i.item_subtotal
      end
    @total_fee = @total + @order.shipping_fee
  end

  def update
    @order = Order.find(params[:id])
    @order.update(order_params)
    redirect_to admin_order_path(@order.id)
  end

  private

  def order_params
    params.require(:order).permit(:is_active)
  end

end

app/controllers/admin/sessions_controller.rb
# frozen_string_literal: true

class Admin::SessionsController < Devise::SessionsController
  # before_action :configure_sign_in_params, only: [:create]

  # GET '/resource/sign_in'
  # def new
  #   super
  # end

  # POST '/resource/sign_in'
  # def create
  # super
  # end

  # DELETE '/resource/sign_out'
  # def destroy
  # super
  # end

  # protected

  # # If you have extra params to permit, append them to the sanitizer.
  # def configure_sign_in_params
  # devise_parameter_sanitizer.permit(:sign_in, keys: [:attribute])
  # end

  def after_sign_in_path_for(resource)
    admin_path
  end

  def after_sign_out_path_for(resource)
    admin_session_path
  end

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :configure_permitted_parameters, if: :devise_controller?

  def after_sign_out_path_for(resource)
    root_path
  end

  private

  def configure_permitted_parameters
    added_attrs = [:last_name, :first_name, :last_name_kana, :first_name_kana, :email, :postal_code, :address, :telephone_number, :password, :password_confirmation]
    devise_parameter_sanitizer.permit :sign_up, keys: added_attrs
    devise_parameter_sanitizer.permit :account_update, keys: added_attrs
  end

end

app/helpers/admin/customers_helper.rb
module Admin::CustomersHelper
end

app/helpers/admin/genres_helper.rb
module Admin::GenresHelper
end

app/helpers/admin/homes_helper.rb
module Admin::HomesHelper
end

app/helpers/admin/items_helper.rb
module Admin::ItemsHelper
end

app/helpers/admin/order_items_helper.rb
module Admin::OrderItemsHelper
end

app/helpers/admin/orders_helper.rb
module Admin::OrdersHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/homes_helper.rb
module HomesHelper
end

app/views/admin/genres/edit.html.erb
<div class="container mt-3">

  <div class="row mt-3 ml-5">
    <h4 class="bg-light">ジャンル編集</h4>
  </div>

  <div class="row my-5">
    <%= form_with model: [:admin, @genre], local: true do |f| %>
      <label class="col-form-label">ジャンル名</label>
      <%= f.text_field :name, class: 'mx-5' %>
      <%= f.submit "変更を保存", class: 'btn btn-success' %>
    <% end %>
  </div>

</div>

app/views/admin/genres/index.html.erb
<div class="container mt-3">

  <div class="row mt-3 ml-5">
    <h4 class="bg-light">ジャンル一覧・追加</h4>
  </div>

  <div class="row my-5">
    <%= form_with model: [:admin, @genre], local:true do |f| %>
      <label class="col-form-label mx-2">ジャンル名</label>
      <%= f.text_field :name, placeholder: "ジャンル名", class: 'mx-5' %>
      <%= f.submit "新規登録", class: 'btn btn-success' %>
    <% end %>
  </div>

  <div class="row my-2">
    <table class="table ml-3 w-25">
      <thead class="thead-light">
        <tr>
          <th>ジャンル</th>
          <th></th>
        </tr>
      </thead>
      <tbody>
        <% @genres.each do |genre| %>
        <tr>
          <td><%= genre.name %></td>
          <td><%= link_to "編集する", edit_admin_genre_path(genre.id), class: 'btn btn-success btn-sm mx-auto' %></td>
        </tr>
        <% end %>
      </tbody>
    </table>
  </div>

</div>

app/views/admin/homes/top.html.erb
<div class="container mt-3">

  <div class="row mt-3 ml-5">
    <h4 class="bg-light">注文履歴一覧</h4>
  </div>

  <div class="row my-3 w-75 mx-auto">
    <table class="table">
      <thead class="thead-light">
        <tr>
          <th>購入日時</th>
          <th>購入者</th>
          <th>注文個数</th>
          <th>注文ステータス</th>
        </tr>
      </thead>
      <tbody>
        <% @orders.each do |order| %>
        <tr>
          <td>
            <%= link_to admin_order_path(order.id) do %>
              <%= order.created_at.strftime('%Y/%m/%d') %>
            <% end %>
          </td>
          <td><%= order.customer.last_name %><%= order.customer.first_name %></td>
          <td><%= order.order_items.sum(:amount) %></td>
          <td><%= order.is_active %></td>
        </tr>
        <% end %>
      </tbody>
    </table>
  </div>

  <div class="pagination my-2 justify-content-center">
    <%= paginate @orders %>
  </div>

</div>

app/views/admin/items/edit.html.erb
<div class="container mt-3">

  <div class="row mt-3 ml-5">
    <h4 class="bg-light">商品編集</h4>
  </div>

  <div class="row w-100 my-3">
    <%= form_with model: [:admin, @item], class: 'form-horizontal mx-auto', local:true do |f| %>

    <div class="form-group row">
      <label class="col-md-5 col-form-label">商品画像</label>
      <div class="col-md-7">
        <%= f.attachment_field :image %>
      </div>
    </div>

    <div class="form-group row">
      <label class="col-md-5 col-form-label">商品名</label>
      <div class="col-md-7">
        <%= f.text_field :name, size: "30" %>
      </div>
    </div>

    <div class="form-group row">
      <label class="col-md-5 control-label">商品説明</label>
      <div class="col-md-7">
        <%= f.text_area :introduction, size: "33x10" %>
      </div>
    </div>

    <div class="form-group row">
      <label class="col-md-5 control-label">ジャンル</label>
      <div class="col-md-7">
        <%= f.select :genre_id, Genre.all.map {|genre| [genre.name, genre.id] }, {include_blank: '--選択してください--'} %>
      </div>
    </div>

    <div class="form-group row">
      <label class="col-md-5 control-label">税抜価格</label>
      <div class="col-md-7">
        <%= f.text_field :price, size: "20" %>円
      </div>
    </div>

    <div class="form-group row">
      <label class="col-md-5 control-label">販売ステータス</label>
      <div class="col-md-7">
        <div class="d-inline mr-3">
          <%= f.radio_button :is_active, true, checked: true %>
          <%= f.label :is_active, '販売中', value: true %>
        </div>
        <div class="d-inline">
          <%= f.radio_button :is_active, false %>
          <%= f.label :is_active, '販売停止中', value: false %>
        </div>
      </div>
    </div>

    <div class="form-group row">
      <div class="col-md-4"></div>
      <div class="col-md-4">
        <%= f.submit '変更を保存', class: 'btn btn-success' %>
      </div>
    </div>

    <% end %>
  </div>

</div>

app/views/admin/items/index.html.erb
<div class="container mt-3">

  <div class="row mt-3 ml-5">
      <h4 class="bg-light">商品一覧</h4>

    <div class="col text-right mr-5">
      <%= link_to "+", new_admin_item_path, class: 'btn btn-light rounded-circle shadow' %>
    </div>
  </div>

  <div class="row my-3">
    <table class="table w-75 mx-auto">
      <thead class="thead-light">
        <tr>
          <th>商品ID</th>
          <th>商品名</th>
          <th>税抜価格</th>
          <th>ジャンル</th>
          <th>ステータス</th>
        </tr>
      </thead>
      <tbody>
        <% @items.each do |item| %>
        <tr>
          <td><%= item.id %></td>
          <td>
            <%= link_to admin_item_path(item.id) do %>
              <%= item.name %>
            <% end %>
          </td>
          <td><%= item.price %></td>
          <td><%= item.genre.name %></td>
          <td>
            <% if item.is_active == true %>
              <p class="text-success">販売中</p>
            <% else %>
              <p class="text-muted">販売停止中</p>
            <% end %>
          </td>
        </tr>
        <% end %>
      </tbody>
      <%= paginate @items %>
    </table>
  </div>

</div>

app/views/admin/items/new.html.erb
<div class="container mt-3">

  <div class="row mt-3 ml-5">
    <h4 class="bg-light">商品新規登録</h4>
  </div>

  <div class="row w-100 my-3">
    <%= form_with model: [:admin, @item], class: 'form-horizontal mx-auto', local: true do |f| %>

    <div class="form-group row">
      <label class="col-md-5 col-form-label">商品画像</label>
      <div class="col-md-7">
        <%= f.attachment_field :image %>
      </div>
    </div>

    <div class="form-group row">
      <label class="col-md-5 col-form-label">商品名</label>
      <div class="col-md-7">
        <%= f.text_field :name, placeholder: "商品名", size: "30" %>
      </div>
    </div>

    <div class="form-group row">
      <label class="col-md-5 control-label">商品説明</label>
      <div class="col-md-7">
        <%= f.text_area :introduction, placeholder: "ここに説明文を記述します", size: "33x10" %>
      </div>
    </div>

    <div class="form-group row">
      <label class="col-md-5 control-label">ジャンル</label>
      <div class="col-md-7">
        <%= f.select :genre_id, Genre.all.map {|genre| [genre.name, genre.id] }, {include_blank: '--選択してください--'} %>
      </div>
    </div>

    <div class="form-group row">
      <label class="col-md-5 control-label">税抜価格</label>
      <div class="col-md-7">
        <%= f.text_field :price, placeholder: "1000", size: "20" %>円
      </div>
    </div>

    <div class="form-group row">
      <label class="col-md-5 control-label">販売ステータス</label>
      <div class="col-md-7">
        <div class="d-inline mr-3">
          <%= f.radio_button :is_active, true, checked: true %>
          <%= f.label :is_active, '販売中' %>
        </div>
        <div class="d-inline">
          <%= f.radio_button :is_active, false, checked: false %>
          <%= f.label :is_active, '販売停止中' %>
        </div>
      </div>
    </div>

    <div class="form-group row">
      <div class="col-md-4"></div>
      <div class="col-md-4">
        <%= f.submit '新規登録', class: 'btn btn-success' %>
      </div>
    </div>

    <% end %>
  </div>

</div>

app/views/admin/items/show.html.erb
<div class="container mt-3">

  <div class="row mt-3 ml-5">
    <h4 class="bg-light">商品詳細</h4>
  </div>

  <div class="row my-5">
    <div class="col-md-3 mx-3">
      <%= attachment_image_tag @item, :image, format: 'jpeg', fallback: "NoImage_stuff.jpg",size: "250x180" %>
    </div>

    <div class="col-md-8">
      <table class="table table-borderless table-sm">
        <tr>
          <th>商品名</th><td><%= @item.name %></td>
        </tr>
        <tr>
          <th>商品説明</th><td><%= @item.introduction %></td>
        </tr>
        <tr>
          <th>ジャンル</th><td><%= @item.genre.name %></td>
        </tr>
        <tr>
          <th>税込価格</br>(税抜価格)</th><td><%= @item.add_tax_price.to_s(:delimited) %>(<%= @item.price %>)円</td>
        </tr>
        <tr>
          <th>販売ステータス</th>
          <td>
            <% if @item.is_active == true %>
              <p class="text-success mb-0">販売中</p>
            <% else %>
              <p class="text-muted">販売停止中</p>
            <% end %>
          </td>
        </tr>
      </table>
      <div class="my-4 w-50 text-center">
        <%= link_to "編集する", edit_admin_item_path(@item), class: 'btn btn-success' %>
      </div>
    </div>
  </div>

</div>

app/views/admin/orders/show.html.erb
<div class="container mt-3">

  <div class="row mt-3 ml-5">
    <h4 class="bg-light">注文履歴詳細</h4>
  </div>

  <div class="row my-3 ml-5">
    <table class="table table-borderless mb-0">
      <tr>
        <th class="col-md-2">購入者</th>
        <td>
          <%= link_to admin_customer_path(@order.customer_id) do %>
            <%= @order.customer.full_name %>
          <% end %>
        </td>
      </tr>
      <tr>
        <th>注文日</th>
        <td><%= @order.created_at.strftime('%Y/%m/%d') %></td>
      </tr>
      <tr>
        <th>配送先</th>
        <td>
          〒<%= @order.postal_code %> <%= @order.address %></br>
          <%= @order.name %>
          </td>
      </tr>
      <tr>
        <th>支払方法</th>
        <td><%= @order.payment %></td>
      </tr>
      <tr>
        <th>注文ステータス</th>
        <td>
          <%= form_with model: @order, url: "/admin/orders/#{@order.id}", local: true do |f| %>
            <%= f.select :is_active, Order.is_actives.keys %>
            <%= f.submit "更新", class: 'btn btn-success btn-sm ml-2' %>
          <% end %>
        </td>
      </tr>
    </table>
  </div>

  <div class="row ml-5">
    <div class="col-md-8 mr-5">
      <table class="table">
        <thead class="thead-light">
          <tr>
            <th>商品名</th>
            <th>単価（税込）</th>
            <th>数量</th>
            <th>小計</th>
            <th>製作ステータス</th>
          </tr>
        </thead>
        <tbody>
          <% @order_items.each do |order_item| %>
          <tr>
            <td><%= order_item.item.name %></td>
            <td><%= order_item.price.to_s(:delimited) %></td>
            <td><%= order_item.amount %></td>
            <td><%= order_item.item_subtotal %></td>
            <td>
              <%= form_with model: order_item, url: admin_order_order_item_path(order_item.id), local: true do |f| %>
              <%= f.select :is_active, OrderItem.is_actives.keys %>
              <%= f.submit "更新", class: 'btn btn-success btn-sm ml-2' %>
              <% end %>
            </td>
          </tr>
          <% end %>
        </tbody>
      </table>
    </div>

    <div class="col-md-3 px-5 d-flex align-items-end">
      <table class="table table-borderless table-sm">
        <tr>
          <th>商品合計</th>
          <td class="text-right"><%= @total.to_s(:delimited) %>円</td>
        </tr>
        <tr>
          <th>配送料</th>
          <td class="text-right"><%= @order.shipping_fee %>円</td>
        </tr>
        <tr>
          <th>ご請求額</th>
          <td class="text-right"><%= @total_fee.to_s(:delimited) %>円</td>
        </tr>
      </table>
    </div>

  </div>

</div>