config/routes.rb
Rails.application.routes.draw do

  root to: 'public/homes#top'

  devise_for :customers, skip: :all

  devise_scope :customer do
    get '/customers/sign_in'     => 'public/sessions#new'
    post '/customers/sign_in'    => 'public/sessions#create'
    delete '/customers/sign_out' => 'public/sessions#destroy'
    get '/customers/sign_up'     => 'public/registrations#new'
    post '/customers'            => 'public/registrations#create'
  end

  scope module: :public do
    resources :items,       only: [:index, :show] do
      resources :cart_items,  only: [:create]
      patch '/cart_items/:id'         => 'cart_items#destroy'
      delete '/cart_items/destroy_all' => 'cart_items#destroy_all'
    end
    resources :cart_items,  only: [:index, :update]
    get  '/orders/thanks'  => 'orders#thanks'
    resources :orders,      only: [:new, :index, :show]
      post '/orders/confirm' => 'orders#confirm'
      post '/orders/decide'  => 'orders#decide'
    resources :addresses,    only: [:index, :create, :edit, :update, :destroy]
    #customersのルーティング
    get '/customers/my_page'     => 'customers#show'
    get '/customers/edit'        => 'customers#edit'
    patch '/customers'           => 'customers#update'
    get '/customers/unsubscribe' => 'customers#unsubscribe'
    patch '/customers/withdraw'  => 'customers#withdraw'
  end

  devise_for :admins, skip: :all
  devise_scope :admin do
    get '/admin/sign_in'     => 'admin/sessions#new',     as: :new_admin_session
    post '/admin/sign_in'    => 'admin/sessions#create',  as: :admin_session
    delete '/admin/sign_out' => 'admin/sessions#destroy', as: :destroy_admin_session
  end
    namespace :admin do
    resources :items,       except: [:destroy]
    resources :genres,      only: [:index, :create, :edit, :update]
    resources :customers,   only: [:index, :show, :edit, :update]
    resources :orders,      only: [:show, :update] do
      resources :order_items, only: [:update]
    end
  end

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html

  get '/admin' => 'admin/homes#top'
  get '/about' => 'public/homes#about'

end

app/models/address.rb
class Address < ApplicationRecord

  belongs_to :customer

  def full_address
    "〒#{self.postal_code}　#{self.address}　#{self.name}"
  end
end

app/models/admin.rb
class Admin < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable,
         :rememberable, :validatable
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/cart_item.rb
class CartItem < ApplicationRecord

  belongs_to :item
  belongs_to :customer

  def item_subtotal
    amount * item.add_tax_price
  end

end

app/models/customer.rb
class Customer < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  has_many :addresses,  dependent: :destroy
  has_many :cart_items, dependent: :destroy
  has_many :orders,     dependent: :destroy

  def full_name
    self.last_name + self.first_name
  end

end

app/models/genre.rb
class Genre < ApplicationRecord

  has_many :items, dependent: :destroy

end

app/models/item.rb
class Item < ApplicationRecord

  belongs_to :genre, optional: true
  has_many :cart_items, dependent: :destroy
  has_many :order_items, dependent: :destroy
  has_many :orders, through: :order_items

  attachment :image

  def add_tax_price
    (self.price * 1.08).round
  end

end

app/models/order.rb
class Order < ApplicationRecord

  belongs_to :customer
  has_many :order_items
  has_many :items, through: :order_item

  enum payment: {クレジットカード: 0, 銀行振込: 1}
  enum is_active: {入金待ち: 0, 入金確認: 1, 製作中: 2, 発送準備中: 3, 発送済み: 4}

end

app/models/order_item.rb
class OrderItem < ApplicationRecord

  belongs_to :order, dependent: :destroy
  belongs_to :item

  enum is_active: {着手不可: 0, 製作待ち: 1, 製作中: 2, 製作完了: 3}

  def add_tax_price
    (self.price * 1.08).round
  end

  def item_subtotal
    amount * item.add_tax_price
  end

end

app/controllers/admin/homes_controller.rb
class Admin::HomesController < ApplicationController
  before_action :authenticate_admin!, except: [:top]

  def top
    path = Rails.application.routes.recognize_path(request.referer)

    if path[:controller] == "admin/customers"
      @orders = Order.where(customer_id: path[:id]).page(params[:page])
    else
      @orders = Order.page(params[:page])
    end
  end

end

app/controllers/admin/items_controller.rb
class Admin::ItemsController < ApplicationController
  before_action :authenticate_admin!

  def index
    @items = Item.page(params[:page])
  end

  def new
    @item = Item.new
  end

  def create
    @item = Item.new(item_params)
    @item.save
    redirect_to admin_item_path(@item.id)
  end

  def show
    @item = Item.find(params[:id])
  end

  def edit
    @item = Item.find(params[:id])
  end

  def update
    @item = Item.find(params[:id])
    @item.update(item_params)
    redirect_to admin_item_path(@item.id)
  end

  private

  def item_params
    params.require(:item).permit(:name, :image, :introduction, :price, :is_active, :genre_id)
  end

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :configure_permitted_parameters, if: :devise_controller?

  def after_sign_out_path_for(resource)
    root_path
  end

  private

  def configure_permitted_parameters
    added_attrs = [:last_name, :first_name, :last_name_kana, :first_name_kana, :email, :postal_code, :address, :telephone_number, :password, :password_confirmation]
    devise_parameter_sanitizer.permit :sign_up, keys: added_attrs
    devise_parameter_sanitizer.permit :account_update, keys: added_attrs
  end

end

app/helpers/admin/customers_helper.rb
module Admin::CustomersHelper
end

app/helpers/admin/genres_helper.rb
module Admin::GenresHelper
end

app/helpers/admin/homes_helper.rb
module Admin::HomesHelper
end

app/helpers/admin/items_helper.rb
module Admin::ItemsHelper
end

app/helpers/admin/order_items_helper.rb
module Admin::OrderItemsHelper
end

app/helpers/admin/orders_helper.rb
module Admin::OrdersHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/homes_helper.rb
module HomesHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>NaganoCake</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>

    <header>
      <nav class="navbar navbar-expand-lg bg-info">
        <div class="container">
          <%= link_to "ながのCAKE", "/", class: 'navbar-brand font-weight-bold text-white' %>

          <% if admin_signed_in? %>
          <ul class="navbar-nav pt-2">
            <li><%= link_to "商品一覧", admin_items_path, class: 'nav-link btn btn-outline-dark btn-sm mx-2' %></li>
            <li><%= link_to "会員一覧", admin_customers_path, class: 'nav-link btn btn-outline-dark btn-sm mx-2' %></li>
            <li><%= link_to "注文履歴一覧", admin_path, class: 'nav-link btn btn-outline-dark btn-sm mx-2' %></li>
            <li><%= link_to "ジャンル一覧", admin_genres_path, class: 'nav-link btn btn-outline-dark btn-sm mx-2' %></li>
            <li><%= button_to "ログアウト", destroy_admin_session_path, method: :delete, class: 'nav-link btn btn-outline-dark btn-sm mx-2' %></li>
          </ul>
          <% elsif customer_signed_in? %>
          <ul class="navbar-nav pt-2">
            <p class="pt-2 mr-5">ようこそ、<%= @customer.last_name %>さん！</p>
            <li><%= link_to "マイページ", customers_my_page_path, class: 'nav-link btn btn-light btn-sm mx-2' %></li>
            <li><%= link_to "商品一覧", items_path, class: 'nav-link btn btn-light btn-sm mx-2' %></li>
            <li><%= link_to "カート", cart_items_path, class: 'nav-link btn btn-light btn-sm mx-2' %></li>
            <li><%= button_to "ログアウト", customers_sign_out_path, method: :delete, class: 'nav-link btn btn-light btn-sm mx-2' %></li>
          </ul>
          <% else %>
          <ul class="navbar-nav py-2">
            <li><%= link_to "About", about_path, class: 'nav-link btn btn-sm btn-light mx-2' %></li>
            <li><%= link_to "商品一覧", items_path, class: 'nav-link btn btn-sm btn-light mx-2' %></li>
            <li><%= link_to "新規登録", customers_sign_up_path, class: 'nav-link btn btn-sm btn-light mx-2' %></li>
            <li><%= link_to "ログイン", customers_sign_in_path, class: 'nav-link btn btn-sm btn-light mx-2' %></li>
          </ul>
          <% end %>
        </div>
      </nav>
    </header>

    <main>
      <%= yield %>
    </main>

    <footer class="bg-info pt-5 mt-auto w-100">
      <div class="container">
      </div>
    </footer>

  </body>

</html>